# Generated by Django 4.2.16 on 2026-04-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_available', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, help_text='e.g. End of day surplus, slight cosmetic imperfections')),
                ('available_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_listings', to='marketplace.product')),
            ],
        ),
    ]
