# Generated by Django 4.2.16 on 2026-04-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_paymentsettlement_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('batch_info', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('resolved', 'Resolved')], default='draft', max_length=20)),
                ('affected_from', models.DateField(blank=True, null=True)),
                ('affected_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='marketplace.producerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='marketplace.product')),
            ],
        ),
    ]
