# Generated by Django 4.2.16 on 2026-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_product_low_stock_threshold_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
