# Generated by Django 4.2.16 on 2026-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: paste a URL to an image for this post'),
        ),
        migrations.AddField(
            model_name='product',
            name='season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
