# Generated by Django 4.2.16 on 2026-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_producerdeliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderitem',
            name='next_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
